name: Bump okp4d version
on:
  workflow_dispatch:
    inputs:
      okp4dVersion:
        description: "Version of okp4d"
        required: true

jobs:
  bumpd-okp4-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OKP4_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.OKP4_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.OKP4_BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Bump okp4d version
        run: |
          dataFile="data/chain.json"
          tmpFile=$(mktemp)

          jq '.okp4dVersion |= "${{ github.event.inputs.okp4dVersion }}"' "$dataFile" > "$tmpFile" &&
          cp "$tmpFile" "$dataFile" &&
          rm -f "$tmpFile"

      - name: Commit okp4d version change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: ${{ secrets.OKP4_BOT_GIT_COMMITTER_NAME }}
          commit_user_email: ${{ secrets.OKP4_BOT_GIT_COMMITTER_EMAIL }}
          commit_author: ${{ secrets.OKP4_BOT_GIT_AUTHOR_NAME }} <${{ secrets.OKP4_BOT_GIT_AUTHOR_EMAIL }}>
          commit_message: "build: bump okp4d version to ${{ github.event.inputs.okp4dVersion }}"
